include:
  - {{ slspath }}/locale
  - {{ slspath }}/timezone
  - {{ slspath }}/keyboard
  - {{ slspath }}/boot
  - {{ slspath }}/swap
  - {{ slspath }}/repositories
  - {{ slspath }}/raspicast
  - {{ slspath }}/media-center
  - {{ slspath }}/pi-hole
  - {{ slspath }}/web-browser
